CRAYSAT-1734: Update bootprep usage docs for multi-arch support
Cray-HPE/docs-sat pull request #111
Opened 2023-06-16 20:42 UTC by haasken-hpe

## Summary and Scope

### CRAYSAT-1734: Document BOS session template `arch` field in bootprep

Document the newly added `arch` field that can be specified at the
boot-set level in the BOS session templates defined in the `sat
bootprep` input file.

Test Description:
Tested modified bootprep input files passed schema validation with the
latest development version of the cray-sat container image.

### CRAYSAT-1734: Document `sat bootprep` base image filter on arch/wildcard

Add documentation on how to use the `arch` and `wildcard` filtering on
base images or recipes provide by a product.

The `wildcard` functionality was added a little while ago, while the
`arch` functionality was just added by CRAYSAT-1718.

Provide examples that are similar to actual use cases that an admin will
encounter when looking at our default `sat bootprep` input files
delivered with the `hpc-csm-software-recipe` release distribution.

Test Description:
Tested modified bootprep input files passed schema validation with the
latest development version of the cray-sat container image.

## Issues and Related PRs

* Resolves [CRAYSAT-1734](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1734)

## Testing

### Tested on:

  * mug

### Test description:

See commit messages.

## Risks and Mitigations

Low risk. Modified examples have been re-tested.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-06-20 19:06 UTC, jack-stanek-hpe approved these changes

2023-06-21 23:15 UTC, jld-dehn-hpe requested changes

2023-06-21 23:15 UTC, jld-dehn-hpe commented on docs/usage/sat_bootprep.md
> +architecture "ARM" in HSM. Note that usage of the `image_ref` key requires that
```suggestion
input file by its `ref_name` and targets nodes with the role `Compute` and the
architecture `ARM` in HSM. Note that using the `image_ref` key requires that
```

2023-06-22 16:33 UTC, haasken-hpe commented on docs/usage/sat_bootprep.md
> +#### Filter Base Images from a Product
What would you think about instead adding a couple other headings above this. They would be:

#### Use Base Images or Recipes from IMS

This one would be before line 174.

#### Use Base Images or Recipes from a Product

This one would be before line 195.

2023-06-22 16:36 UTC, haasken-hpe commented on docs/usage/sat_bootprep.md
> +the IMS recipe provided by the `cos` product of the specified version.
I'll have to check on whether that `x86_64` still needs a backslash with your edit to put it in backticks, but otherwise, looks good.

2023-06-22 16:44 UTC, haasken-hpe commented on docs/usage/sat_bootprep.md
> +#### Filter Base Images from a Product
I made the heading change from your suggestion, but I didn't apply your suggestion in order to also update where it was linked to from other parts of the document. I also added the headings from my comment above. Let me know what you think.

2023-06-22 16:46 UTC, haasken-hpe commented
Thanks for your comments, @jld-dehn-hpe! I believe I've addressed them all. Please take another look.

2023-06-22 19:19 UTC, jld-dehn-hpe approved these changes
Looks good to me, and I really like what you decided to do with the headings!

2023-06-22 19:36 UTC, haasken-hpe commented
/backport release/2.6

2023-06-22 19:41 UTC, merged