CRAYSAT-1591: Document `list-vars`, refer to `docs-csm` for default files
Cray-HPE/docs-sat pull request #45
Opened 2022-10-12 20:41 UTC by jack-stanek-hpe

## Summary and Scope

This change documents `sat bootprep list-vars` for viewing the available variables when processing bootprep input files, without cloning the repository manually.

This change also refers the user to the `docs-csm` guide for viewing the default bootprep input files in order to reduce doc duplication.

## Issues and Related PRs

* Resolves [CRAYSAT-1591](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1591)

## Testing

### Tested on:

  * Local development environment

### Test description:

Build docs, check for errors, and inspect built HTML.

## Risks and Mitigations

None.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-10-13 14:41 UTC, haasken-hpe approved these changes

2022-10-13 14:41 UTC, haasken-hpe commented on docs/sat_bootprep.md
> +can be found in the `bootprep` directory of the cloned repository:
I would consider just condensing this paragraph into the previous one by adding "as described in the ... section of the Cray System Management Documentation." I don't feel like saying the steps is necessary here either as the number of steps could change, and then we'd be out of date here.

2022-10-17 18:51 UTC, jld-dehn-hpe requested changes

2022-10-17 18:51 UTC, jld-dehn-hpe commented on docs/sat_bootprep.md
> +can be found in the `bootprep` directory of the cloned repository:
```suggestion
Documentation*](https://cray-hpe.github.io/docs-csm/). Find the
default input files in the `bootprep` directory of the cloned repository:
```

2022-10-17 18:51 UTC, jld-dehn-hpe commented on docs/sat_bootprep.md
> +subcommand.
Why does `sat-bootprep(8)` include a hyphen, but `sat bootprep list-vars` does not? Just want to confirm this is correct. Also, I have a few wording suggestions below:

```suggestion
values of the keys listed above. View these variables and their values
by running `sat bootprep list-vars`. For more information on options that
can be used with the `list-vars` subcommand, see `sat-bootprep(8)`.
```

2022-10-17 18:51 UTC, jld-dehn-hpe commented on docs/sat_bootprep.md
> +repository, as described in the **Accessing `sat bootprep` files** section of
```suggestion
repository, as described in the **Accessing `sat bootprep` files** process of
```

2022-10-20 16:19 UTC, jld-dehn-hpe commented on docs/sat_bootprep.md
> +subcommand.
I like this rewording...let's go with that.

2022-10-20 16:21 UTC, jld-dehn-hpe approved these changes

2022-10-21 14:19 UTC, merged