STP-3303: Add release notes for SAT 2.4 to integration
Cray-HPE/docs-sat pull request #47
Opened 2022-10-20 23:59 UTC by jld-dehn-hpe

## Summary and Scope

Added release notes documenting the changes in SAT 2.4 from the previous version SAT 2.3.

## Issues and Related PRs

* Resolves [STP-3303](https://jira-pro.its.hpecorp.net:8443/browse/STP-3303)
* Change will also be needed in `release/2.4`

## Testing

Spell check and lint check

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-10-31 16:54 UTC, ekamin-hpe requested changes
A few comments, mostly related to last-minute bug fixes incrementing versions of things.

As for the spell check failures, I think it would be fine to add "traceback", "Artifactory" and CVE ID(s) into the `.spelling` file to define them as exceptions for the spell check.

With the remaining spell check failures, I think we are seeing the issue I described in this conversation: https://github.com/Cray-HPE/docs-sat/pull/34#discussion_r988327357

I think there is some kind of bug in the spell check when it comes to handling links that contain line breaks. For the most part, I think if you just put the entire link on one line that will address these failures, though in the example of lines 33-34 I think that would make the line too long.

There could be a creative way to resolve this (e.g. shortening the link text), but if not I would say it's fine to add e.g. "decoupling-of-cray-sat-container-image-and-cray-sat-podman-package" to the spelling exceptions file as well, ideally with a comment saying this is due to a bug with the spell checker. Even though the spell checker is being a bit too strict here I would prefer to try and keep it passing.

2022-10-31 16:54 UTC, ekamin-hpe commented on docs/release_notes.md
> +- Version 3.19.2 of the `sat` python package and CLI.
```suggestion
- Version 3.19.3 of the `sat` python package and CLI.
```

2022-10-31 16:54 UTC, ekamin-hpe commented on docs/release_notes.md
> +- Version 1.5.4 of the `sat-install-utility` container image.
```suggestion
- Version 1.5.5 of the `sat-install-utility` container image.
```

2022-10-31 16:54 UTC, ekamin-hpe commented on docs/release_notes.md
> +- Version 3.3.0 of the `cfs-config-util` container image.
```suggestion
- Version 3.3.1 of the `cfs-config-util` container image.
```

2022-10-31 16:54 UTC, ekamin-hpe commented on docs/release_notes.md
> +The `paramiko` Python package version was updated from 2.9.2 to 2.10.1 to
Another CVE item could be added here - 

> The `oauthlib` Python package version was updated from 3.2.0 to 3.2.1 to mitigate CVE-2022-36087.

https://github.com/Cray-HPE/sat/blob/release/3.19/CHANGELOG.md#security

2022-11-02 14:21 UTC, jack-stanek-hpe approved these changes
My comments are the same as Eli's. Other than those, I think this looks good!

2022-11-07 22:41 UTC, jld-dehn-hpe commented
@ekamin-hpe, I added your changes and got all the checks to pass. Let me know if there's any other changes you want before approving. Thanks!

2022-11-07 22:43 UTC, ekamin-hpe approved these changes
> @ekamin-hpe, I added your changes and got all the checks to pass. Let me know if there's any other changes you want before approving. Thanks!

Looks good, thanks for taking the time to address both the feedback and the failing checks. Glad it worked!!

2022-11-07 23:05 UTC, merged